baseurl: "/~gadgil/LTS2019"
collections:
  assignments:
      output: true
      permalink: /assignments/:title
  draft-assignments:
      output: false
      permalink: /draft-assignments/:title
  announcements:
      output: true
      permalink: /announcements/:title
  notes:
    output: true
    permalink: /notes/:title
